
spring:
  application:
    name: mesg-service
  cloud:
    nacos:
      discovery:
        username: nacos
        password: nacos
        namespace: public
        ephemeral: true
        server-addr: localhost:8848
  datasource:
    url: jdbc:mysql://localhost:3306/motorhomekun
    username: root
    password: ZWC123456
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 9091
mybatis:
  mapper-locations: classpath:mapper/*.xml
