server:
  port: 9090
spring:
  application:
    name: gateway-service
  cloud:
    sentinel:
      transport:
        dashboard: localhost:30000
    nacos:
      discovery:
        username: nacos
        password: nacos
        namespace: public
        ephemeral: true
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          enabled: true
      #        路由数组
#      routes:
#        - id: test1 #路由唯一标识
#          uri: https://www.baidu.com    #路由转发目标 不是完整地址 服务名
#          predicates: #断言 路由规则匹配
#            - Path=/test/** #只需要localhost:4000/test/xxx
#          #            最终路由地址 http://www.baidu.com/test
#          filters: #过滤器
#            - StripPrefix=1  #去前缀
#
#            ##           -表示yml中地数组
#        - id: user-router
#          #通过负载均衡调用指定服务
#          uri: lb://user-service
#          predicates:
#            - Path=/user-service/**
#          filters:
#            - StripPrefix=1
#        - id: goods-router
#          uri: lb://goods-service
#          predicates:
#            - Path=/goods/**
#          filters:
#            - StripPrefix=1
#        - id: mesg-router
#          uri: lb://mesg-service
#          predicates:
#            - Path=/mesg/**
#          filters:
#            - StripPrefix=1

#        全局跨域
#        globalcors:
#          cors-configurations:
#            '[/**]':
#              allowedOrigins: "*"         #允许跨域来源
#              allowedMethods:            #允许请求方式
#                - GET
#                - POST
#                - PUT
#                - DELETE


#        discovery:
#          locator:
#            enabled: true



#